name: Update PDF

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  
jobs:
  html-to-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: html to pdf
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./public/index.html
          outputFile: ./public/resume.pdf
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
          
      - name: Save last date
        run: echo $(date +"%Y-%m-%d %H:%M:%S %Z") > public/date.txt

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: master
          commit_options: '--no-verify --signoff'
          file_pattern: public/*
          commit_message: "Update PDF"
