name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  html-to-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: html to pdf
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./public/index.html
          outputFile: ./public/resume.pdf
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
          
      - name: Save last date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d') > ./public/date.txt"


